web:
  build: .
  command: python app.py
  volumes:
    - .:/my_application
  links:
    - postgres:postgres
  ports:
    - "5000:5000"

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
